name: Refresh Class Access Tokens

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch: 

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Install TypeScript
        run: npm install -g typescript

      - name: Transpile TypeScript to JavaScript
        run: tsc src/Flow/Flow.ts
        
      - name: Run Script
        run: node src/Flow/Flow.js
